language: go
os:
  - linux
  - osx
go:
  - 1.5
  - tip
notifications:
  slack:
    secure: oCFqpjl7o6RC5fkx3kVu70AmdW+SezTUrE2iKqsXTnK6Bfrq+uisXRQyndSoN7LP5VUxiA8trvJBdWKHZveqrbfpyyBv/D30/o4dI0EKG4fR0k9ZTrbg2QQ48FUm97cJK3EzI4UrNS8kUdfWLzrrJ13VaMYM5rKf9hiGaBrhnFUSpJ/3tVgonSOBnHLqzie9AlInF5cpLM3Zep64f9ly70R2Mo1U7IWMEQr6F5ijoMwo3P81MeaaHrdcDghcaQ6JNlA/ZdJ9VpoA2E5PRzy3nqnlORb6wNSEli7icjGErgwRZGK0TeWjgadKlXVjpKosNEknnQz+WhxSjTmilBu/qhjOqJqOsaUYreB03FrxatF89c3GgMvI+J5iuFdN4mm+KrcFuNC+VHeK/QjNYHsCWvB0HqOXQtLh1zomrh8RTbJTgT7cJu+8tqQFFtrI2D6HT9D9P84/6/mx0bo0PFaoiNrIUXojc2P78Vy7lIq38oSiDA2kEzDpZQrVHT3e8QTfNtb8FUqkBGohhuQT34oDVL7IwHpvp/AKe5rMJSMjJBfgM/qu8CHdn6jH3cYimhTbc+VplWayMMEDrwYvIwqglV/oOzfkg5HWV8Aha8b7gF2h6lwaVI8c+51nOuE9L4pON3ByHV3aUk2w0ow01O0OFaa4mPDKNXkgcH44miZ+UXs=
